{
 "title": "Client Metrics",
 "refresh": "5s",
 "panels": [
  {
   "title": "Records Processed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (customer) (rate(statements_processed_total[1h]))",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Error Rate of Processed Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by (customer) (rate(process_errors_total[1h])) / sum by (customer) (rate(statements_processed_total[1h]))) * 100",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Open Positions Per Month",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (customer) (increase(open_positions[1h]))",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Closed Positions Per Month",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (customer) (increase(closed_positions_total[1h]))",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "ERP Service HTTP Responses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code,endpoint,customer) (rate(erp_http_responses_total[1m]))",
     "legendFormat": "HTTP {{status_code}} {{endpoint}} {{customer}}"
    }
   ]
  }
 ]
}