{
 "title": "Internal Metrics",
 "refresh": "5s",
 "panels": [
  {
   "title": "System Availability",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "((sum(statements_processed_total) - sum(process_errors_total)) / sum(statements_processed_total)) * 100"
    }
   ]
  },
  {
   "title": "Validation Worker Success Rate (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "((sum(rate(validate_success_total[1m])) - sum(rate(validate_failed_total[1m]))) / sum(rate(validate_success_total[1m]))) * 100"
    }
   ]
  },
  {
   "title": "ERP Worker: API Success Response Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(erp_http_responses_total{status_code='200'}[1m])) / sum(rate(erp_http_responses_total[1m]))) * 100"
    }
   ]
  },
  {
   "title": "Unique Logins/Sessions by Location",
   "type": "geomap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "unique_logins_total{}" }
   ]
  },
  {
   "title": "CPU Usage Over Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "worker_cpu_usage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Memory Usage Over Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "worker_memory_usage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Network Throughput Over Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "worker_network_throughput", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Hourly Active Users",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (location) (increase(unique_logins_total[1h]))",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Total Transactions Processed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(statements_processed_total)"
    }
   ]
  },
  {
   "title": "Total Positions Open Per Month",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(increase(open_positions[1h]))"
    }
   ]
  },
  {
   "title": "Total Positions Closed Per Month",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(closed_positions_total[1h]))"
    }
   ]
  },
  {
   "title": "Model Correctness Over Time (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(model_correctness_ratio) * 100",
     "legendFormat": "{{customer}}"
    }
   ]
  }
 ]
}